---
abstract: 'Hookable variant of the Perl core regular expression engine.'
author:
  - 'Vincent Pit <perl@profvince.com>'
build_requires:
  Carp: 0
  DynaLoader: 0
  ExtUtils::Depends: 0
  ExtUtils::MakeMaker: 0
  File::Spec: 0
  POSIX: 0
  Test::More: 0
  blib: 0
configure_requires:
  ExtUtils::Depends: 0
  ExtUtils::MakeMaker: 0
  File::Spec: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.64, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: re-engine-Hooks
no_index:
  directory:
    - t
    - inc
requires:
  Carp: 0
  DynaLoader: 0
  perl: 5.010001
resources:
  bugtracker: http://rt.cpan.org/NoAuth/ReportBug.html?Queue=re-engine-Hooks
  homepage: http://search.cpan.org/dist/re-engine-Hooks/
  license: http://dev.perl.org/licenses/
  repository: http://git.profvince.com/?p=perl%2Fmodules%2Fre-engine-Hooks.git
version: 0.04
